distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.10/apache-maven-3.9.10-bin.zip
distributionSha256Sum=4e0d2e1a9e79c3b7e1eb4d30c510b63c1b50c9cca8bf8d55a6b620c730baf52f
